### ISSUE TITLE
Refiner des not display full path for Managed Metadata Column with display full path option

### ISSUE THREAD

**Issue by coupalm** [SharePoint/sp-dev-solutions#155] opened 2019-05-13 16:32 UTC
#### Category
- [ ] Question
- [X] Bug
- [X] Enhancement

#### Expected or Desired Behavior
If managed metadata column is set to display full path, refiner should also display full path term.

#### Observed Behavior
Refiners only display term and not fullpath. This only occurs when using the TaxId managed property and not the label property.

#### Steps to Reproduce
Set the managed metadata column display option to full path. Configure managed property to use the taxId crawl property. Configure refiner using the TaxId managed property.

**Comment by FranckyC** [comment] 2019-05-15 13:41
Hi @coupalm. Not a bug since it is not implemented. I will add it to the roadmap.

**Comment by FranckyC** [comment] 2019-05-15 13:46
We will see if a simple solution exists since this option is at the column level and not on managed property.

**Comment by wobba** [comment] 2019-10-03 11:06
Closing this one as you need to map `ows_columnName` for the full path. And the roadmap item stays for adding extra logic to enable this.

**Closed by wobba** 2019-10-03 11:06 UTC
