### ISSUE TITLE
Modern search handlebars template getDate format not working

### ISSUE THREAD

**Issue by mrik23** [SharePoint/sp-dev-solutions#143] opened 2019-05-02 08:38 UTC
@FranckyC @wobba

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Date should be formatted when using getDate token in handlebars template.  

`<span>{{getDate BirthDay "MMMM DD"}}</span>`

#### Observed Behavior
The date formatting is breaking in some cases, once it doesn't display correctly in a browser, it seems like I can't get it to have it working again for a particular page.

Date is showing up but in full default format.

`5/3/2019 12:00:00 AM`

#### Steps to Reproduce
Seems like the problem only occurs on other page than Home.aspx.

**Comment by wobba** [comment] 2019-05-02 10:35
@mrik23 Date type managed properties return data on the form `2018-09-10T06:29:25.0000000Z`. If you use automatically created date properties like `CreatedOWSDATE` it works just fine.

**Comment by wobba** [comment] 2019-05-02 10:37
I updated the docs to reflect this.

**Comment by FranckyC** [comment] 2019-05-06 19:41
Does it work for you @mrik23?

**Comment by mrik23** [comment] 2019-05-15 06:16
@FranckyC @wobba Also I noticed that the doc is saying that there is an option to load handlebar helpers but I don't see it in the styling options.

![image](https://user-images.githubusercontent.com/13704404/57752521-ae11d900-7713-11e9-9d77-a962d1527d57.png)

**Comment by wobba** [comment] 2019-05-15 08:16
@mrik23 we should update the docs, as it's loaded dynamically if you use one of the functions provided from handlebar helpers.

**Comment by mrik23** [comment] 2019-05-15 10:15
@wobba OK that's an old option. Could that the root cause of my issue? if it's not get loaded?

**Comment by wobba** [comment] 2019-05-15 10:45
@YannickRe I tried adding a result wp + pagination (hooked to the result wp) to a page. Set query to `*` and 5 results. Seems when I click the pagination nothing happens. (dev branch)

**Comment by YannickRe** [comment] 2019-05-15 10:51
@wobba You don’t change pages or the you can reproduce the dateformat issue?

**Comment by wobba** [comment] 2019-05-15 10:53
@YannickRe I only get page 1 :) There are no ajax calls fetching page 2 etc. So hard to reproduce. Formatting works fine on page 1.

**Comment by YannickRe** [comment] 2019-05-15 10:54
Assign to me, I’ll try and figure this out today/tomorrow evening.

**Comment by wobba** [comment] 2019-05-15 11:53
@YannickRe I can't officially assign it, but it's your and we should probably create a new issue(s). One for pagination and one for dateformatting on page two etc, if it can be reproed.

**Comment by YannickRe** [comment] 2019-05-15 13:44
@wobba just to make sure: you connected the page webpart to the result webpart (to display paging) AND you connected results to paging (to act on page change)?

It feels like you didn’t do the second connection... Can you conform?

**Comment by wobba** [comment] 2019-05-15 14:05
@YannickRe connected both ways now, still nothing. 
![image](https://user-images.githubusercontent.com/51104/57781796-30f25e00-772b-11e9-93c9-f2830a7b7395.png)

**Comment by FranckyC** [comment] 2019-05-15 14:52
@wobba wrong place to connect the pagination WP. Go to page 3 ;)

![image](https://user-images.githubusercontent.com/5659122/57785291-75680480-76ff-11e9-8c79-e413ebac0396.png)

**Comment by wobba** [comment] 2019-05-15 15:45
@FranckyC I'll try that. Hard stuff 😉

**Comment by YannickRe** [comment] 2019-05-16 06:27
I have no issues with pagination (on dev branch) 😉

Currently, I have tested the following Handlebars code:
```
<span>Date 1: {{CreatedOWSDate}}</span>
<span>Date 1 formatted: {{getDate CreatedOWSDate "MMMM DD"}}</span>
<span>Date 2: {{Created}}</span>
<span>Date 2 formatted: {{getDate Created "MMMM DD"}}</span>
```
It results in the following output, on all pages:
```
Date 1: 2017-10-18T10:37:47Z
Date 1 formatted: October 18
Date 2: 2017-10-18T10:37:47.0000000Z
Date 2 formatted: October 18
```

I cannot reproduce it yet, but I have added some RefinableDate mapped properties and waiting for reindexing.

**Comment by wobba** [comment] 2019-05-16 06:34
@mrik23 I've tested it now. Paging works. When the date shows up in full format, it's because moment was not able to parse it.

```
let d = (<any>window).searchHBHelper.moment(date, format, { lang: this.CurrentLocale, datejs: false });
```

Parsing uses the locale of English.

So for those display full string, is there a difference between how the raw value looks compared to those that work?

**Comment by mrik23** [comment] 2019-05-16 13:01
@wobba no, it's the same value. It words on one page, but not another one.

Also I noticed the formatting works in SharePoint mobile app, but not in the browser.

@YannickRe Thanks for talking the time to map some properties :) I hope you will be able to reproduce.

So far I really don't understand as the same template works fine on one page, and can't get it to work on another page or site.

**Comment by mrik23** [comment] 2019-05-16 13:09
@YannickRe by the way, first time I apply the custom template, it displays just fine (in edit mode). If I save and refresh the page, the dates will show not formatted.
So it seems like a problem with the handlebar helper, maybe not loading. Just strange it doesn't show an error.

**Comment by mrik23** [comment] 2019-05-16 13:27
@wobba @YannickRe I created a new page and a test template for demo.

Example template:

```
<div>
    {{#each items}}
    <div>
        <div>
            {{#if BirthDay}}
            <span>Birthday: {{BirthDay}}</span><br>
            {{/if}}
            {{#if BirthDay}}
            <span>Birthday formatted: {{getDate BirthDay "MMMM DD"}}</span><br>
            {{/if}}
            {{#if HireDate}}
            <span>HireDate: {{HireDate}}</span><br>
            {{/if}}
            {{#if HireDate}}
            <span>HireDate formatted: {{getDate HireDate "YYYY-MM-DD"}}</span><br>
            {{/if}}
            <br>
        </div>
    </div>
    {{/each}}
</div>
```
Result in edit mode:
![image](https://user-images.githubusercontent.com/13704404/57856926-3b3e5600-7818-11e9-99d5-66481c1141d4.png)

Formatting happening.

Result in view mode after refresh:
![image](https://user-images.githubusercontent.com/13704404/57856962-54470700-7818-11e9-92d8-c3d4d4f6a3a4.png)

Formatting not working.

Hope that clarifies the problem.

**Comment by YannickRe** [comment] 2019-05-16 13:56
Thank you for the detailed explanation and screenshots. It'll take me some time, so please be patient (maybe @wobba can help you out sooner), I'm swamped atm with other stuff that takes priority ☹.

**Comment by wobba** [comment] 2019-05-16 17:04
What language is the site/user UI?

**Comment by YannickRe** [comment] 2019-05-16 18:58
I cannot reproduce this issue ☹. I tested with your template, on an English communication site and a Dutch teamsite, with a user that has English and another user that has Dutch as his UI language. All tested on a new page within those sites (not the homepage).

@wobba Only thing I can now imagine that might trigger an issue has to do with the naming of the Handlebars helpers. I don't know a lot about Handlebars, so I might be wrong.

We are loading our own helper named getDate, based on moment.js:
https://github.com/SharePoint/sp-dev-solutions/blob/9dda60162575c62bab0f713893385bcec2b04871/solutions/ModernSearch/react-search-refiners/spfx/src/services/TemplateService/BaseTemplateService.ts#L133-L142

We are also loading an out of the box helper named getDate:
https://github.com/SharePoint/sp-dev-solutions/blob/9dda60162575c62bab0f713893385bcec2b04871/solutions/ModernSearch/react-search-refiners/spfx/src/services/TemplateService/BaseTemplateService.ts#L184-L186

Might it be that those collide in some way?

**Comment by wobba** [comment] 2019-05-16 19:48
Hmm...I believe I added that as our getDate is using helpers - to trigger a load.

I think we should log the error in the catch to see why it fails. @mrik23 can you debug from SPFX and see what the error in the catch is..would be useful. Or see if console says anything.

**Comment by mrik23** [comment] 2019-05-29 04:04
@wobba @YannickRe Yes I could change the code to console log the error, I will try to free some time for this.

**Comment by sympmarc** [comment] 2019-06-14 20:28
I cant get dates to format, either. I'm trying to format the Start Date and End Date for events.  I think these should work?
`{{getDate EventDateOWSDATE "MM-DD-YYYY"}}`
`{{getDate EndDateOWSDATE "MM-DD-YYYY"}}`

No matter how I try things, I'm still seeing dates like "2019-06-18T17:00:00.0000000Z"

**Comment by sympmarc** [comment] 2019-06-14 20:35
Ok, this is weird. I switched back to the "list" format and then back to my custom template. All of a sudden, the date formatting started working. No idea why.

**Comment by wobba** [comment] 2019-06-14 20:48
Weird and something to look into for sure.

**Comment by sympmarc** [comment] 2019-06-14 20:59
It's consistent. At least I've got a way to make progress, but it would be nicer if it didn't do this. :)

**Comment by sympmarc** [comment] 2019-06-16 19:38
For whatever reason, this ghost in the machine seems to have disappeared. I'm finding the easiest change/view approach is to stay in edit mode and flip back to Tiles, then to Custom again each time I make a change to the Handlebars template.

**Comment by wobba** [comment] 2019-06-18 06:26
@sympmarc seems like there's something iffy with a state in edit mode for the template we need to track down and fix.

**Comment by momo258** [comment] 2019-07-03 15:28
It seems like the function LoadHandlebarsHelpers does not get called.
This code thats responsible for calling this function. Can be found in BaseTemplateService.ts
```
   let regEx = new RegExp("{{#.*?" + element + ".*?}}", "m");
            if (regEx.test(templateContent)) {
                await this.LoadHandlebarsHelpers();
                break;
            }
```

Example :
Regex : `/{{#.*?getDate.*?}}/m`
Doesn’t match with `{{getDate EventDateOWSDATE "MM-DD-YYYY"}}`
The reason for this is because of ” # ” been part of the Regex.
If you remove “ # ” from the Regex than it will match correctly.
Afterword’s LoadHandlebarsHelpers will be called and your dates will format.

**Comment by wobba** [comment] 2019-07-03 15:40
@momo258 great find! I'll try get a fix in for this tomorrow.

**Comment by FranckyC** [comment] 2019-07-03 15:42
Good catch @momo258! Effectivelly, the issue is the searchHBHelper object is not created and the getDate helper relies on it.

**Comment by wobba** [comment] 2019-07-04 10:39
Fixed and will be part of the next release

**Closed by wobba** 2019-07-04 10:39 UTC
Labels: bug

**Comment by mrik23** [comment] 2019-07-08 08:31
@wobba OK I will update when the release is made available.

**Comment by roberAlb** [comment] 2021-02-03 07:44
This issue is happening for us today,  we have webpart version 3.15.1.0  and the dates are coming with this format  "28/01/2021 00:00:00 Z" , they were fine 2 days ago as far as we know.

**Comment by mloslier** [comment] 2021-02-03 10:39
The issue is happening for us too from Today. But all results are not impacted.
![image](https://user-images.githubusercontent.com/77447270/106735337-641e0480-6614-11eb-810e-f0bc5b862aba.png)

**Comment by wobba** [comment] 2021-02-03 12:22
@mloslier if data is changing in how it's returned in the API, that is outside of this project. You should log a support ticket about this.
