### ISSUE TITLE
People template: Disable info on hover not working

### ISSUE THREAD

**Issue by webbrewer** [SharePoint/sp-dev-solutions#375] opened 2020-02-11 04:39 UTC
#### Category
- [ ] Question
- [X] Bug
- [] Enhancement

#### Expected or Desired Behavior

Enabling display info on hover should open the details dialog (similar to people web part)

#### Observed Behavior

Enabling info on hover doesn't work.

#### Steps to Reproduce

Create people results source and add to results web part ContentClass=urn:content-class:SPSPeople
Select "people" template

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment] 2020-02-11 08:50
If this is related to Modern Search, file the issue over at https://github.com/microsoft-search/pnp-modern-search.

We don't have hover information implemented today, and using the people hover from the platform is a technical challenge. It's tracked at https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/38451154-provide-support-for-livepersonacard-in-3rd-party-s and I'm trying to make it available for 3rd party use.

Closing as this is not a bug, but a feature request - and I'm following up on it.

**Closed by wobba** 2020-02-11 08:50 UTC
