### ISSUE TITLE
[Modern Search] Date filter

### ISSUE THREAD

**Issue by BraunJonathan** [SharePoint/sp-dev-solutions#106] opened 2019-04-03 12:35 UTC
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Very nice additon with this date filter, clearly something our users were really asking for, thank you !!
But i found a few bugs around this functionnality : 
- i have several other refiners and when other refiners got recalculate to reflect the results filtered by date, my date choice is not displayed anymore
- when i filter by date, my property "technical" name is shown below the filter button and not the actual date or at least the displayValue of the refiner...
![image](https://user-images.githubusercontent.com/35366413/55479155-bc9da880-561d-11e9-9212-ee807f95e257.png)

**Comment by FranckyC** [comment] 2019-04-03 12:49
Hi @BraunJonathan Thank you for your feedback. For the first issue, I'll investigate. If could provide me a quick scenario to be able to reproduce this behavior, would be nice. For the second, this is not really a bug but the current implementation logic for the "Panel" layout. Maybe I should display the selected dates as well then. Normally, you should see selected dates by re opening the panel.

**Comment by BraunJonathan** [comment] 2019-04-03 12:58
Hi @FranckyC 
Thanks for the quick answer !
For the second problem for other refiners, it's the value which is displayed and for the date, it is the technical property value (LastModifiedDateForRetention when my displayname is "Date de modification"). Displaying the selected date would, i think, be the best option though !

For the first problem, i got a bunch of  other refiners and when i use the date filter to actually filter data, te refiners panel is refreshed to only show things related to actual results and then my date values disapear...
I guess if you create multiple results with mulitple users at different dates and add a ModifiedBy Filter, you should be able to reproduce the problem...

**Comment by BraunJonathan** [comment] 2019-04-03 13:11
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35366413/55481452-bbbb4580-5622-11e9-8322-91c0f6ba978e.gif)

**Comment by BraunJonathan** [comment] 2019-04-03 13:17
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/35366413/55481855-85ca9100-5623-11e9-88b1-eb074f1b2d18.gif)

**Comment by FranckyC** [comment] 2019-04-04 13:04
@BraunJonathan Thanks for the capture. I'm not able to reproduce your issue but I identified an other bug where the filter value is lost when you collapse/expand the refiner header. Maybe it is related. I'm working on it but at first glance, it is not that simple than it looks like.

**Comment by BraunJonathan** [comment] 2019-04-04 13:55
@FranckyC Yes i've got this bug too, could be the same problem as both look like a refresh problem. I had a look at the code, and it did not look simple to me either ;-)
I guess the dateRange component must be recreated somewhere along the rerendering way...

**Comment by FranckyC** [comment] 2019-04-04 14:01
@BraunJonathan The issue is on the Office UI Fabric 'GroupedList' component who mount/unmount the children components every time you collapse/expand so they lose their state. Don't know if it is a bug or the expected behavior. I'll keep you posted.

**Comment by BraunJonathan** [comment] 2019-04-04 14:42
@FranckyC Ok thanks for the diagnosis !
Seems indeed tricky to solve... Maybe you can use  the selected filters to reset the correct value when redisplaying the groupList ?
Regarding my initial problem, when i filter my results, sometimes when the number of groups changes, the Linkpanel seems to not be able to find out which Group was open or not and then shows everyone collapsed, resulting in the bug you've noticed... I'll have a look to see if i can find what's really causing the problem...

**Comment by BraunJonathan** [comment] 2019-04-04 15:02
@FranckyC 
Ok i got the original problem which is quite simple... When the refinementResult length changes (like when all results do not have the same metadata), the number of groups isn't the same anymore and the id, which is used to "store" the collapsed info changes... It is not found into the expandedGroups state property and therefore is shown collasped running into the other bug you noticed...
Maybe if the expandedGroups state property was storing the groupName instead of the index, we could be able to found the group even if it has not the same id...
I'll give it a try...

**Comment by FranckyC** [comment] 2019-04-04 15:55
Thank you for the update. I'll take a look ASAP. Also, if you find a way to solve this issue, feel free to make a PR ;)

**Comment by FranckyC** [comment] 2019-04-04 22:59
@BraunJonathan Should be fixed now. Just let me know if everything work as expected on your side.

**Comment by BraunJonathan** [comment] 2019-04-05 06:19
PR is not merged yet but i looked at the commits and it seems ok, i was working in that direction yesterday evening ;-)
Thanks for the really fast fixes !!

**Comment by wobba** [comment] 2019-04-05 06:33
@BraunJonathan I'll merge once merge conflicts are resolved.

**Comment by BraunJonathan** [comment] 2019-04-05 06:36
@wobba Yeah, i've seen that, fixes were already lightning fast so i can wait a little, no worries ;-)

**Comment by FranckyC** [comment] 2019-04-05 13:23
@wobba @BraunJonathan ready to merge

**Closed** 2019-04-05 13:37 UTC

**Comment by BraunJonathan** [comment] 2019-04-05 14:08
@FranckyC it seems you forgot a semicolumn in LinkPanel.tsx but otherwise, it seems to work like a charm :-)
Thanks a lot for this and for the whole work !!

**Comment by FranckyC** [comment] 2019-04-05 16:34
De rien @BraunJonathan ;)
