### ISSUE TITLE
I couldn't see my custom taxonomy metadata property as search refiner

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-solutions#236] opened 2019-07-25 22:15 UTC
The custom taxonomy metadata are not available under the search refiner when my search results returning all the document which has the custom taxonomy property set. 

#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

The search refiner should display my custom taxonomy metadata property as an option under the 'Search Refiner' when the search results returns the documents which has the custom metadata property value set. 

#### Observed Behavior

In my case i have 2 custom taxonomy called Document Type and Business Area. The both taxonomy metadata is not displaying under the search refiner but the default property such as 'File Type' are showing under the search refiner.

#### Steps to Reproduce

1. Created custom taxonomy metadata called Document Type in terms store
![image](https://user-images.githubusercontent.com/22563887/61910136-af3d5e80-af2b-11e9-9eb0-bd1a28f6f46a.png) 
2. Create custom site column for managed metadata  called 'Document Type' and mapped the 'Document Type' taxonomy metadata
3. Create site content type called 'My Document'
4. Add custom site column which was created in step 2 to the site content type ('My Document')
5. Create document library on the site called 'My library'
6. Add the site content type ('My Document' to the newly created document library 'My Library'
7. Upload documents to the library and set the document content type to 'My Document'
8. Update the metadata property to each document accordingly
9. Add the refinable crawled property for this newly created taxonomy metadata under Search Schema - eg. RefinableString00 and mapped to 'ows_taxId_DocumentType'
![image](https://user-images.githubusercontent.com/22563887/61910724-4d7df400-af2d-11e9-9990-fda5788a5fb1.png)
9. Wait couple of minutes or hours to make sure the contents are crawled 
10. Create a page and add the 'Search Refiner', 'Search Box' and 'Search Results' webpart.
11. configure the webparts accordingly
12 Note: Make sure add the custom taxonomy metadata property under the 'Search Refiner' configuration and save
![image](https://user-images.githubusercontent.com/22563887/61911055-2f64c380-af2e-11e9-9b29-b9a4cfeacfc5.png)
13. Save the page and try to search for the document which was uploaded in My library

I have been trying  to figure out this for more than a week not but no luck. I don't know what am i missing. I hope someone could help me or point me to the right direction.

Thank you in advanced.

**Comment by FranckyC** [comment] 2019-07-25 22:51
Hi @muges01, if you inspect the underlying 'postquery' REST call response in the network tab of you browser, can you see refinement results? You can also check if there is a value for this property using the [search query tool](https://github.com/SharePoint/PnP-Tools/tree/master/Solutions/SharePoint.Search.QueryTooll. Last thing, make sure your current query actually gets results. A common mistake is to leave the default Path:{Site} query template as is that only performs a search in the current site and not giving expected results.

**Comment by muges01** [comment] 2019-07-25 23:13
Hi @FranckyC ,

I have inspect the underlying 'postquery' REST call response in the network tab, it is returning the refinement results but it is not returning the custom metadata refiner.
![image](https://user-images.githubusercontent.com/22563887/61914809-b4090f00-af39-11e9-8870-23cabcd80b8e.png)

I can confirm that the search results are returning the documents which has the custom property set.

**Comment by FranckyC** [comment] 2019-07-25 23:14
Remove the Path:{Site} from the query template if present and retry.

**Comment by FranckyC** [comment] 2019-07-25 23:15
Also, are documents checked-in and published?

**Comment by muges01** [comment] 2019-07-26 00:13
Hi @FranckyC ,

I have removed the Path:{Site} and still the same. all the document are published,

I'm getting the documents in my results but i'm not getting my custom taxonomy metadata under my refiner.

![image](https://user-images.githubusercontent.com/22563887/61916922-87a5c080-af42-11e9-89ef-46e833e5f839.png)

![image](https://user-images.githubusercontent.com/22563887/61916927-8f656500-af42-11e9-879f-59290e61c794.png)

**Comment by FranckyC** [comment] 2019-07-26 00:25
Can you check if you have data for this managed property using search query tool. Also check if your search schema is not overwritten somewhere (site collection vs global).

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by muges01** [comment] 2019-07-27 22:29
Hi @FranckyC 

I checked using the 'Search Query Tool' and i'm not getting any data for the managed property.

**Comment by wobba** [comment] 2019-07-28 07:50
@muges01 If you specify RefinableString00 in the query tool and get no results, then the property contains no value, hence not a bug with this web part. You may also map the ows_DocumentType column which has the textual value only, and see if that yields results.

**Comment by muges01** [comment] 2019-07-30 22:56
Hi @wobba, 

Sorry for the late reply. 

Could it be that the search crawled is not picking this managed metadata fields. I couldn't find the ows_DocumentType in my RefinableString00. Currently only the ows_taxId_DocumentType' is mapped to  the RefinableString00.

thank you
muges

**Comment by wobba** [comment] 2019-07-31 06:26
Can you check that the mp `owstaxIdSiteColumnName` has a value? That is the automatically generated managed property for your site column. If it does, then you need to re-index. Also, at what level did you map the cp to the mp, vs the scope you are searching from?

**Comment by muges01** [comment] 2019-07-31 07:02
Hi @wobba,

I manage to search the document using this field value. One more information, I can filter the results using the ows_tax_documenttype value which was return under the ‘Tags’ thou. I have try to re-index the site as well. I created a classic site and create page with refiner webpart. When I try to configure the refiner I notice there is no value for Refineablestring00 property which I map taxonomy property. 

By the way my taxonomy called DocumentType and the site column is called DocumentType. Can this cause any issue?

What do you mean by ‘what level did you map the cp to the mp, vs the scope you are searching from’?

**Comment by wobba** [comment] 2019-08-05 13:47
You can map crawled properties on site, site collection and tenant level (https://www.techmikael.com/2016/02/search-schema-mapping-level-explained.html)

Which means the mapping must appear at the same level or a higher level for the item in question vs. the URL you are searching from.

If Refineablestring00 is empthy then you either:
* mapped the wrong crawled property
* item with data set is not a major version
* item was indexed before the mapping

The easiest test is to create a new item after the mapping, and the use the SharePoint Query Tool or similar to see that RefinableString00 actually has a value for the indexed item.

**Comment by muges01** [comment] 2019-08-20 21:30
Hi @wobba, 

Sorry for the late reply, i was moving to new location. 

The RefinableString00 is empty. I have checked the following:
- mapped the wrong crawled property (I have mapped to 'ows_taxId_DocumentType', i can't find any other property to map. example ows_DocumentType)
- item with data set is not a major version (It is a major version)
- item was indexed before the mapping (I have re-index the site)

Note: I'm using site column which is mapped to global taxonomy

Any other suggestion?

**Comment by wobba** [comment] 2019-08-21 06:05
How do you know it's re-indexed? ;) Create a new item, wait for it to be searchable, and then the managed property should contain a value. You do not say at what level (tenant/site) you did the mapping, nor where the search box sits (site url).

**Comment by wobba** [comment] 2019-08-21 06:06
Either way, closing the issue as it's not related to the web parts themselves.

**Closed by wobba** 2019-08-21 06:06 UTC

**Comment by muges01** [comment] 2019-08-21 19:59
Hi Wobba, 

I have raise a support ticket with Microsoft and they said they re-index them, so i know for sure that it was re-indexed. I mapped it at tenant level.

Yes, looks like it is not the issue with the web parts but it is something wrong on the tenant. 
The support ticket with Microsoft now. Thank you for the guidance.
