### ISSUE TITLE
Applying JSON Properties to Search Box / Search Refiner WebParts problem

### ISSUE THREAD

**Issue by GeoffE1e6** [SharePoint/sp-dev-solutions#59] opened 2019-02-20 12:44 UTC
Category
- [x] Question
- [x] Bug
- [ ] Enhancement

Hi Folks,

Am working on a mechanism to deploy using PNP the search refiner webpart with the search box based on its web properties to another site. This is to ensure that the configuration can be replicated programmatically, without having to manually re-enter all the settings for the search refiner and search box.

To do this, I extracted the PropertiesJSON from the Search Box and the Search Results with Refiners on an existing page using Get-PnPClientSideComponent.

Then, I recreated the page on another site, added the Search Box and Search Results with Refiners webparts and applied the JSON using Set-PnPClientSideWebPart.

I've run into some problems:
1: The web parts cannot be configured; the configuration panel will not display.
2: If the page is Saved as Draft, a serialization error is displayed. Also, the Search Refiner is not keeping its state; the data source is not being set dispite that having entries in the JSON. Am guessing this is because the JSON included the ID of Search Box it was connected to, which will be different for Search Box on the new page...

#### Steps to Reproduce
1: Create a new site page called Home;
2: Add the Search Box and Search Refiners web part onto the Home page;
3: Using Get-PnPClientSideComponent, extract the JSON for both web parts;
4: On a new site, create the site page called Home.
5: Add the Search Box and Search Refiners web part onto this Home page;
6: Using Set-PnPClientSideWebPart, set the PropertiesJSON property to the JSON extracted in step 3 above.

Can anyone please advise what the best method would be to apply JSON obtained from these webparts to the same placed webparts on a different page?

**Comment by tdwhite0** [comment] 2019-03-04 21:49
@GeoffE1e6 I had problems getting this WebPart to export/import correctly too. What I found that was in the properties JSON wasn't getting exported with a "queryKeywords" property, I think because of the dynamic data setup. When I added that manually to  the properties I was able to get the import to work.

**Comment by YannickRe** [comment] 2019-03-31 13:47
@tdwhite0 Your analysis is partly correct. The queryKeywords property is supposed to be absent in the properties export, because it is the fallback property/static value for a dynamic property.
A correct export would have been something like this:
```
{
    "properties": {

    },
    "dynamicDataPaths": {}, 
    "dynamicDataValues": {
        "queryKeywords":"*";
    }
}
```
The root cause is that currently PnP .net (and thus PnP PowerShell) doesn't support exporting and importing web parts with dynamic data connections. My pull request that adds support (https://github.com/SharePoint/PnP-Sites-Core/pull/2120) has been merged and should be dropped into the April 2019 release and then trickle down into the PnP PowerShell release (no idea how fast they adopt the new dll).

@GeoffE1e6 Long story short: your approach is correct and the root cause isn't the web parts. Next month you should be able to do this 😉

**Comment by YannickRe** [comment] 2019-04-06 05:34
@GeoffE1e6 @tdwhite0 It got released with [SharePointPnPCoreOnline ](https://www.nuget.org/packages/SharePointPnPCoreOnline/3.8.1904) and [SharePointPnPPowerShellOnline](https://www.powershellgallery.com/packages/SharePointPnPPowerShellOnline/3.8.1904.0) 3.8.1904! Have fun exporting ;)

@wobba I think this can be closed now.

**Closed** 2019-04-06 06:49 UTC
