### ISSUE TITLE
SPFx React Search WebPart: Page.Property-Token not working

### ISSUE THREAD

**Issue by schneika** [SharePoint/sp-dev-solutions#281] opened 2019-09-02 12:57 UTC
Regarding SPFx React Search Refiner WebPart:
I cannot handle the Page.Property Token in Search Result WebPart
 
#### Category
- [ ] Question
- [x ] Bug
- [] Enhancement

#### Observed Behavior 

The Query Template 
`{searchTerms} owstaxIdipiPublishingBrand:Labels`
works well and i get related content (relevant 43 Results).

ipiPublishingBrand is the internal Fieldname for a Managed Metadata Column.
 
![image](https://user-images.githubusercontent.com/11440416/64115736-aa709380-cd90-11e9-9b2c-a241431713f7.png)

With the Query Template
`{searchTerms} owstaxIdipiPublishingBrand:{Page.ipiPublishingBrand}` or
`{searchTerms} owstaxIdipiPublishingBrand:{Page.ipiPublishingBrand.Label}` (for Term-Label)
in order to filter the query on an existing Page Property Value i get no search results and error s.indexOf is not a function
![image](https://user-images.githubusercontent.com/11440416/64115953-47cbc780-cd91-11e9-81bf-2a8ea17c1f70.png)

It seems, that the Page.Property-Token not working as expected in the search results webparts?

**Comment by FranckyC** [comment] 2019-09-02 13:32
@schneika Is it a multi taxonomy value?

**Comment by schneika** [comment] 2019-09-02 13:46
No is explicit a Single Value Taxonomy Field. In Content and Page Property

Otherwise the User.Property-Token is working as expected.
A Query Template like 
{searchTerms} owstaxIdipiPublishingBrand:{User.ipiPublishingBrand} 
delivers expected Search results regarding the Taxonomy-Value in my custom Delve/User Profile Property

But the Page.Property Token i cant get working...

**Comment by wobba** [comment] 2019-09-02 14:07
@schneika duplicate of #269. Fix will arrive in next version.

**Closed by wobba** 2019-09-02 14:07 UTC
