### ISSUE TITLE
Use of {{getUrlField}} helper in custom results layout: error/no display of search results

### ISSUE THREAD

**Issue by ewkohtz** [SharePoint/sp-dev-solutions#154] opened 2019-05-13 14:38 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._

Modifying custom Results layout in the Modern Search results, adding {{getUrlField}} helper should result in the display of the Title or URL portion of a URL managed property as specified in the helper.

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

After adding the managed property URLOWSURLH to the Selected Properties window,
Then adding 

<span class=""><span>{{URLOWSURLH}}</span></span> 

in the custom Results layout, I AM ABLE to display the comma separated Title and URL values of the URLOWSURLH managed property:  

However, using one or both of the following handlebar entries, I am unable to return the individual Title or URL values of this managed property:

<span class=""><span>{{getUrlField URLOWSURLH "URL"}}</span></span>
<span class=""><span>{{getUrlField URLOWSURLH "Title"}}</span></span>

This causes all results to no longer display.

The following error results in code viewer console:

Unhandled promise rejection TypeError: Unable to get property 'indexOf' of undefined or null reference
search-box-web-part_7a7b305b25413178f964ea5ab5c1027c.js (51,70744)
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to get property 'indexOf' of undefined or null reference",
      message: "Unable to get property 'indexOf' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'indexOf' of undefined or null reference
   at Anonymous function (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:51:164234)
   at Function code (Function code:3:3)
   at s (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:12247)
   at o.data[partial-block] (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:12918)
   at s (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:13173)
   at o (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:10007)
   at Function code (Function code:3:3)
   at s (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:12247)
   at i.eq (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/1.search-handlebars-helpers_054259651d152bb3ef3b.js:403:2681)
   at Function code (Function code:3:3)"
   }

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

1) Ensure creation and population of items within a Links list.  
2) Add URLOWSURLH to the Selected Properties of Search Results settings
3) Add <span class=""><span>{{URLOWSURLH}}</span></span> helper to  custom Results layout.
4) Validate Title and URL values of URLOWSURLH managed property display on search results.  
5) Add <span class=""><span>{{getUrlField URLOWSURLH "URL"}}</span></span>  AND/OR
<span class=""><span>{{getUrlField URLOWSURLH "Title"}}</span></span> to custom Results layout.
6) Validate no search results or information displays, as well as error .

**Comment by wobba** [comment] 2019-05-14 07:55
@ewkohtz I tried with this template:

```html
<div class="template_root">
	{{#each items as |item|}}
		{{URLOWSURLH}}<br>
		{{getUrlField URLOWSURLH "URL"}}<br>
		{{getUrlField URLOWSURLH "Title"}}<br>
	{{/each}}
</div>
```

which gave the following output
```
https://www.puzzlepart.com, Puzzlepart
https://www.puzzlepart.com
Puzzlepart
```

Tested with the code in the dev branch, and with v2.2.0.1. So any pointers on how to reproduce it would help.

**Comment by ewkohtz** [comment] 2019-05-15 19:52
@wobba thanks for the response.  I'm not sure what else to point to for repro.  

To rule out any template issues, I applied your simplified code alone to custom the Results layout.  
First using only: 
```
<div class="template_root">
	{{#each items as |item|}}
		{{URLOWSURLH}}<br>
	{{/each}}
</div>
```
...which results in the following comma-separated output:

![Capture](https://user-images.githubusercontent.com/45462866/57802698-ca157a80-7713-11e9-8bc0-ae031fdfc98c.PNG)

However, if I re-add the getURLField references:

```
<div class="template_root">
	{{#each items as |item|}}
		{{URLOWSURLH}}<br>
		{{getUrlField URLOWSURLH "URL"}}<br>
		{{getUrlField URLOWSURLH "Title"}}<br>
	{{/each}}
</div>

```
the results go blank.  
![Capture](https://user-images.githubusercontent.com/45462866/57801842-f3350b80-7711-11e9-8534-c24b6a690841.PNG)

again, with the following error:
```
Unhandled promise rejection TypeError: Unable to get property 'indexOf' of undefined or null reference
search-results-web-part_cb124146f064d4658932a6c6fc911df6.js (51,71468)
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         message: "",
         name: "TypeError"
      },
      description: "Unable to get property 'indexOf' of undefined or null reference",
      message: "Unable to get property 'indexOf' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'indexOf' of undefined or null reference
   at Anonymous function (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:51:164234)
   at Function code (Function code:3:3)
   at s (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:12247)
   at o (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:6002)
   at Anonymous function (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:6463)
   at Function code (Function code:3:3)
   at o (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:10411)
   at r (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:10621)
   at n (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:50:49548)
   at Anonymous function (https://microncorp.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_cb124146f064d4658932a6c6fc911df6.js:51:166277)"
   }
```
I'm happy to provide any additional info that you think may be helpful.

**Comment by wobba** [comment] 2019-05-15 19:59
@ewkohtz any particular items you bring back? Any with a comma in the text perhaps? If you're a dev testing in debug with a breakpoint could help.

**Comment by ewkohtz** [comment] 2019-05-15 21:06
@wobba  Thanks for this suggestion!  The search term I was using was returning link items that are formatted as 'tinyurl' in the URL:
```
http://tiny/url?ckmjm, Data science for leaders
http://tiny/url?ckmjn, Effective Data Presentation​
```
When I use a term that returns a URL without the question mark, the result is displays with the appropriate 'getURLField' properties.   

With this in mind, is there any option for dealing with this or other characters that may cause the result to fail?

**Comment by wobba** [comment] 2019-05-16 06:35
@ewkohtz I'll check it out

**Comment by wobba** [comment] 2019-05-25 12:15
@ewkohtz I tried with the latest dev branch. Added the `URL` column to a list, added data and cannot reproduce it. Tested in Chrome and IE11 with the template you pasted.

![image](https://user-images.githubusercontent.com/51104/58369198-53d4fd00-7ef7-11e9-9a2a-a5b647c0dea9.png)

**Comment by wobba** [comment] 2019-07-05 10:28
@ewkohtz still and issu or can I close this one?

**Closed** 2019-08-09 07:33 UTC
Labels: needs-investigation
