### ISSUE TITLE
Question on {Page.Term} not working Term tokens with relationships

### ISSUE THREAD

**Issue by vano76** [SharePoint/sp-dev-solutions#269] opened 2019-08-21 21:08 UTC
#### Category
- [x] Question
- [ ] Bug
- [] Enhancement

I have a question about using the {Page.<Field>.Label} . It doesn't seem to be working for me. I have added a custom Managed Property and I am using that with the {Page.customProp.Label}. Is that supposed to work? After looking at the examples in says to use the internal column name which I have also tried but that doesn't work for me either. Also going a step further are there tokens that can be used with terms such as Term.Children or Term.Siblings or Term.Parent? I am working on building a dynamic portal, The web parts are awesome thanks for all of the work on them.

**Comment by wobba** [comment] 2019-08-22 06:41
Hi,
When you add `{Page..Label}` in your query template. Can you check the network trace for `_/_api/web/GetList(@v1)/RenderExtendedListFormData` calls and see if the value has been picked up or not? That query is used to load page tokens.

**Comment by vano76** [comment] 2019-08-22 19:19
@wobba  That helps, thank you. I have not been able to get any of the Tokens to work. The only documentation I have found is the PnP Video which I have watched. Are there any examples that anyone could point me to? I have tried {Page.fieldname} and Created:{CurrentYear} and a multitude of others and it doesn't seem like any of the tokens are working in my KQL Query. It's very possible I am doing something wrong. Any guidance and/or examples that anyone could provide would be greatly appreciated.

Specifically what I am looking to do is to look at the term that the current page is tagged with and display documents with the same tag. The example in the video is {Page.fieldname.Label}.

**Comment by wobba** [comment] 2019-08-22 20:36
I think we could extend the debug template to show the values of the query variables used in the query template. And, make sure they are in the template field, not the query text one. Maybe we should add a test for that as well and show a warning.

**Comment by vano76** [comment] 2019-08-23 18:57
@wobba That would be awesome, I have been working on trying to figure out what is happening. Is there anyway to debug what is returned by the tokens or to see the value of the tokens? I was playing around and when I am using the {Page} token it is returning documents that have undefined in the title so I am assuming it is returning undefined also I have had it return Object. It would be really useful to find a way to display the values of the tokens BTW the debug template is awesome. Using the Query Search Tool in has also helped try and determine what is happening but at the moment seems like the tokens are kind of a black box. I have tried the Network tab and using the React browser extension but haven't been able to track the tokens as of yet. Thanks for your responses to this.

**Comment by wobba** [comment] 2019-08-23 19:21
Page tokens are custom implemented, and loaded with the call I listed. You can monitor the _api/search network calls and see what's passed in the actual query.

**Comment by wobba** [comment] 2019-08-27 05:47
Thank you for troubleshooting this and definitely something we should fix.

**Comment by wobba** [comment] 2019-08-28 09:16
The issue was if the column was missing or if the column value was not set for an item. Added fixes for both.

**Comment by NeoLegolas** [comment] 2019-09-16 08:48
@wobba I tried the dev branch built as well but still Page token doesn't work. Issue still exist.

**Comment by wobba** [comment] 2019-09-16 10:11
@NeoLegolas Could you check the network trace for calls to `/_api/web/GetList(@v1)/RenderExtendedListFormData(itemId=` and look at the response coming back. Look for data related to the field you are using in the Page token.

**Comment by NeoLegolas** [comment] 2019-09-16 12:50
{"@odata.context":"https://devtopsoe.sharepoint.com/sites/tools/_api/$metadata#Edm.String","value":"{\"ListData\":{\"owshiddenversion\":150,\"ContentType\":\"Site Page\",\"FileLeafRef\":\"How-do-i-get-insurance.aspx\",\"Title\":\"How do i get insurance\",\"ContentCategory\":\"How-to guide|a4bf0b11-f711-4031-9a18-eaafa31d6a81\",\"Department\":\"\",\"HowToGuide\":\"Denmark|fe6842a0-5126-4d5f-bb9a-a99aa95a81cf\",\"Location\":\"Lyngby|8b51c628-8a7a-4425-825f-8ec02be3ba37\",\"MainBusiness\":\"\",\"Topic\":\"Travel|5e624ea6-bb84-4ae8-9d2e-416edae0df0b\",\

**Comment by NeoLegolas** [comment] 2019-09-16 12:51
Just a part of the Response you asked...I can see the metadata columns getting the values in this call correctly.

**Comment by wobba** [comment] 2019-09-16 18:08
Hi,
So seems you can use Page.ContentCategory/HowToGuide/Location/Topic which should return values for you. Are you saying they are not? What is the token you are using?

**Comment by NeoLegolas** [comment] 2019-09-16 18:43
Hi,
I tried all of these... {Page.Topic.Label} , {Page.HowToGuide.Label} etc.... In return I get nothing.. Page.Topic.Label has a value "Travel"..If I write travel my query works but not with token...

Get Outlook for Android<https://aka.ms/ghei36>




On Mon, Sep 16, 2019 at 11:38 PM +0530, "Mikael Svenson" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
So seems you can use Page.ContentCategory/HowToGuide/Location/Topic which should return values for you. Are you saying they are not? What is the token you are using?

**Comment by NeoLegolas** [comment] 2019-09-17 07:45
@wobba The issue is now resolved. We debugged the code on our end and found that the data coming in item was in lowercase. So {Page.topic.Label} return the correct value instead of {Page.Topic.Label}.

**Comment by wobba** [comment] 2019-09-17 08:38
@NeoLegolas I'll add a fix for this, which will be part of v3.7. Thank you for debugging this :)

**Closed by wobba** 2019-09-17 08:38 UTC
