### ISSUE TITLE
Refiner WebPart Not Displaying Results

### ISSUE THREAD

**Issue by gristy58** [SharePoint/sp-dev-solutions#288] opened 2019-09-06 07:01 UTC
#### Category
- [ ] Question
- [x] Bug
- [] Enhancement

#### Expected or Desired Behavior

Refiner webpart is configured with several refiners, when a search is performed these refiners should be displayed.

#### Observed Behavior

From time to time (quite frequently). The refiners will flash up and then go blank. Refreshing the same page 1-2 times will bring the refiners back and make them persistent.

Refreshing the page can also make the refiners disappear.

I cannot see anything different in the developer console between the two outcomes

I have a search results webpart that is taking querys from a query string, a pagination webpart and a refiner webpart.

If i toggle off "show blank if no result" i will get no filter available.

I believe it looks like a timing issue i.e. the check to show nothing is happening before results are returned to the web part and therefore hides the filters despite them being there - is there a way for this section of code to be more robust?

**Comment by wobba** [comment] 2019-09-06 10:31
Can you check that the managed property you add as a refiner is set to be a refinable property. Also, verify your query and refiner part using for example the SharePoint Query Tool. If you get values there, then you should in the web part. If the tool shows now values, then it's a mistake somewhere on the managed property setup.

**Comment by gristy58** [comment] 2019-09-06 10:41
Hi wobba

The refiners are all refinable and work perfectly say 7/10 times with the same query.

When they do not display they do flash on the screen before the webpart hides them.

It appears to be a bug in the refiner webpart it is hiding the refiners as it thinks there is none despite displaying them for a second. I suspect that the code being used to check if there are refiners is running too quickly 3/10 times.

I can get my developer to build us a version fixing this bug if someone can point me to the code that is causing this behavior

**Comment by wobba** [comment] 2019-09-06 13:04
@gristy58 The code is using dynamic data to send data from the result wp to the refiner wp. Question is why it fails at times. Does it fails on full page refresh, or also on onpage searches when you change the query in the search box? Any error in the console, and when it fails, do you see data coming back on the _api/search request?

**Comment by gristy58** [comment] 2019-09-06 19:30
Like I say the refiners flash up as expected quickly and disappear I can then refresh and they display OK

I will record a video today

**Comment by wobba** [comment] 2019-09-06 19:47
I belive you, but without getting debug data via network trace etc, or steps to reproduce it, we cannot really help.  A video showing the flash won't help much.

**Comment by gristy58** [comment] 2019-09-06 22:57
how would i capture that?

**Comment by gristy58** [comment] 2019-09-06 22:58
https://youtu.be/K_jcIUsSwag

**Comment by gristy58** [comment] 2019-09-07 02:40
interestingly classic old school edge works OK everytime.

**Comment by gristy58** [comment] 2019-09-07 03:07
Here is a fiddler trace https://kkit365-my.sharepoint.com/:f:/g/personal/chris_grist_kkit_com_au/Eo7Vslf-RsxMpdiEVWWQALwB5ImHyMY1Y2-aIQVIJCIJgg?e=4siDyI

**Comment by wobba** [comment] 2019-09-07 08:00
@gristy58 F12 for dev tools in any browser, network tab, look for _api/search queries. Look at the returned value. Or use SharePoint Search Query Tool, with same settings, and look at returned data.

**Comment by gristy58** [comment] 2019-09-07 11:47
Ok will do more tomorrow.

The results page is using query string called Search and any query dies it but I just use a path against the document library

**Comment by wobba** [comment] 2019-09-08 07:09
Ok, so a doc lib, where columns are mapped to refinablestrings? And you are using the latest version (3.6.3)?

**Comment by gristy58** [comment] 2019-09-08 09:42
That is correct I believe I am using the last one published as a package 3.6.0 will test with latest as soon as I can

**Comment by gristy58** [comment] 2019-09-08 09:45
yes 3.6.3.0

**Comment by gristy58** [comment] 2019-09-08 09:50
also uploaded chrome network exports at the link above

**Comment by wobba** [comment] 2019-09-09 12:04
@gristy58 I've managed to reproduce it - which is a good step :) Now to figure out a solution.

**Comment by gristy58** [comment] 2019-09-09 12:08
Awesome always a good first step!

**Comment by wobba** [comment] 2019-09-09 14:13
I think I'm close to perhaps do a band-aid on it. Will test more tomorrow. Not sure of the exact root cause yet.

**Comment by wobba** [comment] 2019-09-10 09:47
@gristy58 Can you pull down the modern-search-dev branch and rebuild and see if the issue is resolved for you?

**Comment by gristy58** [comment] 2019-09-10 11:54
Ok will give it a go may not get on my Dev machine for a little while tho any chance of a package file

**Comment by wobba** [comment] 2019-09-10 16:05
@gristy58 https://1drv.ms/u/s!AsQPRl4COMyeopt1YsVWmhs4vB_sAA?e=al7WTf

**Comment by gristy58** [comment] 2019-09-10 21:14
perfection mate :)

**Comment by wobba** [comment] 2019-09-11 05:29
I'll close this then

**Closed by wobba** 2019-09-11 05:29 UTC
